name: K6 Performance Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:   
    - cron: '0 12 * * *'

jobs:
  run-test:
    name: Run Performance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 22
        uses: actions/setup-node@v4
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup K6
        uses: grafana/setup-k6-action@v1.1.0
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1.1.3
        with:
          node-version: 22
          cache: 'npm'
          path: src/tests
      - run: npm run ci